# Generated by Django 3.2.5 on 2021-08-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0002_categoria_producto_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
