# Generated by Django 3.2.5 on 2021-08-25 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasEnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapi.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
