# Generated by Django 3.2.5 on 2021-08-25 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0004_comprasenc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasenc',
            options={'verbose_name_plural': 'Encabezados de Compras'},
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapi.proveedor'),
        ),
        migrations.CreateModel(
            name='ComprasDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='djapi.comprasenc')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djapi.producto')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Compras',
            },
        ),
    ]
