GET http://127.0.0.1:8000/rest/v1/docs/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI3OTkzMzQ1LCJqdGkiOiJmNDVmNDEzMDU5OGM0ZGMzOTA4MWFlM2IwYWEwYjI5NiIsInVzZXJfaWQiOjF9.55wF84qxBcVhXD2G6nbV8BroIBRIsCew5HXO4g4ASKU

GET http://127.0.0.1:8000/rest/v1/docs/3/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI2NzgwMzcyLCJqdGkiOiI4ZDc1YjQ2N2Q5OWQ0YWJiYWM2ZDJiNDAzYmJiZTZmMiIsInVzZXJfaWQiOjJ9.In7vEa-rNKLeX7PIsyPYXlMwOBY31FRWfjehSO0Agps



POST http://127.0.0.1:8000/rest/v1/docs/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI3OTkzMzQ1LCJqdGkiOiJmNDVmNDEzMDU5OGM0ZGMzOTA4MWFlM2IwYWEwYjI5NiIsInVzZXJfaWQiOjF9.55wF84qxBcVhXD2G6nbV8BroIBRIsCew5HXO4g4ASKU

{
    "nombre": "Tercer Documento",
    "expira": "2020-08-05",
    "alerta1y": false,
    "alerta6m": true,
    "alerta3m": false,
    "alerta1m": false
}



PUT http://127.0.0.1:8000/rest/v1/docs/1/
Content-Type: application/json

{
    "nombre": "Primer Documento",
    "expira": "2030-08-05",
    "alerta1y": true,
    "alerta6m": false,
    "alerta3m": false,
    "alerta1m": true
}

DELETE http://127.0.0.1:8000/rest/v1/docs/3/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI3NzM5NDUyLCJqdGkiOiJkZTk3N2ZlN2E3NDk0YzgwOWI2ODYwMjBiNDc1MDAyYyIsInVzZXJfaWQiOjF9.T2Ts3fW7M2XhkzhdMy0s5qF5aR2qZH-bIBWEpXTJqgs


POST  http://127.0.0.1:8000/rest/v1/token/
Content-Type: application/json

{
    "username":"jorge",
    "password":"kate1532"
}

######################################################################

GET http://127.0.0.1:8000/rest/v1/categoria/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI4ODYyMzYzLCJqdGkiOiI5MmUzMmJkMjg4M2Y0M2UzOTM0YTA4MWVlMmIwMDhjZSIsInVzZXJfaWQiOjF9.6-vtcUxPcEH70zaAxXYdiRIt_i-6db17cuHD8lgDyS8


POST  http://127.0.0.1:8000/rest/v1/token/
Content-Type: application/json

{
    "username":"jorge",
    "password":"kate1532"
}



POST http://127.0.0.1:8000/rest/v1/categoria/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI4ODYyMzYzLCJqdGkiOiI5MmUzMmJkMjg4M2Y0M2UzOTM0YTA4MWVlMmIwMDhjZSIsInVzZXJfaWQiOjF9.6-vtcUxPcEH70zaAxXYdiRIt_i-6db17cuHD8lgDyS8

{
    "descripcion": "Categoria de prueba"
}




# superuser = kinudata
# password = kinudata1532

# user = jorge
# password = kate1532